library(readr)
data <- read.table("/Users/siamaktalebi/Downloads/household_power_consumption.txt",sep = ";",header = TRUE,stringsAsFactors = FALSE)
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data <- with(data,data[ymd(Date) >= "2007-02-01" & ymd(Date) <= "2007-02-02",])
data$Global_active_power <- as.numeric(data$Global_active_power)
data$DateTime = as.POSIXct(paste(data$Date,data$Time))
data <- subset(data,select = -c("Date","Time"))
par(mfrow=c(2,2))
plot(data$DateTime,data$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(data$DateTime,data$Voltage, type="l", xlab="datetime", ylab="Voltage")
##PLOT 3
plot(data$DateTime,data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(data$DateTime,data$Sub_metering_2,col="red")
lines(data$DateTime,data$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3"),lty=c(1,1), lwd=c(1,1))
plot(data$DateTime,data$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png,file = "plot4.png",width=480, height=480)
dev.off()
