library(readr)
data <- read.table("/Users/siamaktalebi/Downloads/household_power_consumption.txt",sep = ";",header = TRUE,stringsAsFactors = FALSE)
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data <- with(data,data[ymd(Date) >= "2007-02-01" & ymd(Date) <= "2007-02-02",])
data$Global_active_power <- as.numeric(data$Global_active_power)
data$DateTime = as.POSIXct(paste(data$Date,data$Time))
data <- subset(data,select = -c("Date","Time"))
with(data,plot(DateTime,Sub_metering_1,type = "n",ylab = "Energy sub metering",xlab = ""))
with(data,points(DateTime,Sub_metering_1,type = "l"))
with(data,points(DateTime,Sub_metering_2,type = "l",col = "red"))
with(data,points(DateTime,Sub_metering_3,type = "l",col = "blue"))
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.copy(png,file = "plot3.png",width=480, height=480)
dev.off()
