library(readr)
data <- read.table("/Users/siamaktalebi/Downloads/household_power_consumption.txt",sep = ";",header = TRUE,stringsAsFactors = FALSE)
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data <- with(data,data[ymd(Date) >= "2007-02-01" & ymd(Date) <= "2007-02-02",])
data$Global_active_power <- as.numeric(data$Global_active_power)
data$DateTime = as.POSIXct(paste(data$Date,data$Time))
data <- subset(data,select = -c("Date","Time"))
with(data,hist(Global_active_power,xlab = "Global Active Power (kilowatts)",main ="Global Active Power",col = "red"))
dev.copy(png,file = "plot1.png",width=480, height=480)
dev.off()
